title: Hardhik Mohanty
description: "Ph.D. Candidate, USC — Machine Learning & Quantitative Research for DeFi"
author: Hardhik Mohanty
email: hmohanty@usc.edu

url: "https://hardhik-99.github.io"
baseurl: "/hmohanty"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
