title: Hardhik Mohanty
logo: /assets/img/hm.jpg
description: ""
show_downloads: false
theme: jekyll-theme-minimal

# Hide default theme footer elements
github:
  is_project_page: false
  is_user_page: false
  repository_name: ""
  repository_url: ""
  owner_name: ""
